### ISSUE TITLE
Startup Crash

### ISSUE THREAD

**Issue by LurkerMurker7** [scj643/plugin.video.vrv#7]
I get the following errors when trying to start the VRV addon. I have not been able to get it up running yet. I haven't looked through the entire log below is just what I thought might be important and be causing the crash. I would love to get this working for me a media center without VRV is just not worth it. 
Thanks in advance for any help!

EDIT:Sorry this was on a Raspberry Pi 3 b Kodi L8.0.1 LibreElec 6.0.1

2019-04-14 05:07:50.692 T:1937703584   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2019-04-14 05:07:51.816 T:1500509040   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'oauth_token'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.vrv/addon.py", line 49, in <module>
                                                __settings__.getSetting('oauth_secret'))
                                              File "/storage/.kodi/addons/plugin.video.vrv/resources/lib/vrvlib.py", line 54, in __init__
                                                self.login(email, password)
                                              File "/storage/.kodi/addons/plugin.video.vrv/resources/lib/vrvlib.py", line 60, in login
                                                self.session.auth.client.resource_owner_key = self.auth['oauth_token']
                                            KeyError: 'oauth_token'
                                            -->End of Python script error report<--
2019-04-14 05:07:52.104 T:1456468848   ERROR: GetDirectory - Error getting plugin://plugin.video.vrv/
2019-04-14 05:07:52.105 T:1937703584   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrv/) failed

**Comment by brandontolbird** [comment]
Sorry for not seeing this earlier, but this error indicates that the login has failed. Check your username and password in addon settings.
